export const EXERCISE_MAP = {
  bicep_curl: {
    down_angle: 160,
    up_angle: 50,
    ideal_rom: 110,
    rom_tolerance: 18,
    ideal_tempo: 1.2,
    strict_form_max_deviation: 15,
    strict_form_penalty: 12,
    calibration_margin: 5,
    mode: "curl",
  },
  pushups: {
    up_angle: 155,
    down_angle: 90,
    ideal_rom: 65,
    rom_tolerance: 14,
    ideal_tempo: 1.2,
    strict_form_max_deviation: 12,
    strict_form_penalty: 10,
    calibration_margin: 4,
    mode: "pushup",
  },
  squats: {
    up_angle: 160,
    down_angle: 90,
    ideal_rom: 70,
    rom_tolerance: 16,
    ideal_tempo: 1.3,
    strict_form_max_deviation: 12,
    strict_form_penalty: 10,
    calibration_margin: 4,
    mode: "squat",
  },
  shoulder_press: {
    down_angle: 80,
    up_angle: 160,
    ideal_rom: 80,
    rom_tolerance: 18,
    ideal_tempo: 1.1,
    strict_form_max_deviation: 12,
    strict_form_penalty: 10,
    calibration_margin: 4,
    mode: "press",
  },
  lateral_raise: {
    down_angle: 30,
    up_angle: 80,
    ideal_rom: 50,
    rom_tolerance: 14,
    ideal_tempo: 1.1,
    strict_form_max_deviation: 12,
    strict_form_penalty: 10,
    calibration_margin: 4,
    mode: "raise",
  },
  lunges: {
    up_angle: 165,
    down_angle: 100,
    ideal_rom: 65,
    rom_tolerance: 16,
    ideal_tempo: 1.3,
    strict_form_max_deviation: 12,
    strict_form_penalty: 10,
    calibration_margin: 4,
    mode: "squat",
  },
  front_raise: {
    down_angle: 25,
    up_angle: 80,
    ideal_rom: 55,
    rom_tolerance: 14,
    ideal_tempo: 1.1,
    strict_form_max_deviation: 12,
    strict_form_penalty: 10,
    calibration_margin: 4,
    mode: "raise",
  },
  deadlift: {
    down_angle: 60,
    up_angle: 165,
    ideal_rom: 105,
    rom_tolerance: 18,
    ideal_tempo: 1.5,
    strict_form_max_deviation: 20,
    strict_form_penalty: 12,
    calibration_margin: 5,
    mode: "hinge",
  },
  tricep_extension: {
    down_angle: 60,
    up_angle: 155,
    ideal_rom: 95,
    rom_tolerance: 16,
    ideal_tempo: 1.1,
    strict_form_max_deviation: 12,
    strict_form_penalty: 10,
    calibration_margin: 4,
    mode: "press",
  },
};

export const EXERCISE_LABELS = {
  bicep_curl: "Bicep Curl",
  pushups: "Pushups",
  squats: "Squats",
  shoulder_press: "Shoulder Press",
  lateral_raise: "Lateral Raise",
  lunges: "Lunges",
  front_raise: "Front Raise",
  deadlift: "Deadlift",
  tricep_extension: "Tricep Extension",
};

export const EXERCISES = Object.keys(EXERCISE_LABELS);

export const VISIBILITY_THRESHOLD = 0.6;
